// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XClone.Domain.Database.SqlServer.Context;

#nullable disable

namespace XClone.Domain.DataBase.SqlServer.Migrations
{
    [DbContext(typeof(XcloneContext))]
    partial class XcloneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__Block__3214EC0776BB5928");

                    b.HasIndex("BlockedId");

                    b.HasIndex(new[] { "BlockerId", "BlockedId" }, "UQ_Block")
                        .IsUnique();

                    b.ToTable("Block", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("UserHighId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserLowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Chat__3214EC0776BB5929");

                    b.HasIndex("UserHighId");

                    b.HasIndex(new[] { "UserLowId", "UserHighId" }, "UQ_Chat")
                        .IsUnique();

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__City__3214EC07613F193A");

                    b.HasIndex("CountryId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CommunityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Communit__3214EC0782DCD705");

                    b.HasIndex("CreatorId");

                    b.ToTable("Community", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.CommunityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Member");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CommunityId", "UserId" }, "UQ_CommunityMember")
                        .IsUnique();

                    b.ToTable("CommunityMember", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Country__3214EC075BB97812");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.EmailTemplate", b =>
                {
                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("EmailTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailTemplateId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Following", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Followin__3214EC07B693DCF0");

                    b.HasIndex("FollowedId");

                    b.HasIndex(new[] { "FollowerId", "FollowedId" }, "UQ_Following")
                        .IsUnique();

                    b.ToTable("Following", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Hashtag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Hashtag__3214EC0785CF5CF9");

                    b.HasIndex(new[] { "Texto" }, "UQ__Hashtag__5176E454EBBC9D2B")
                        .IsUnique();

                    b.ToTable("Hashtag", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Like__3214EC077DEA8B2E");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "UQ_Like")
                        .IsUnique();

                    b.ToTable("Like", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__MediaFil__3214EC07A6F47867");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("MediaFile", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Mention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Mention__3214EC07E4792387");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "UQ_Mention")
                        .IsUnique();

                    b.ToTable("Mention", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ParentId" }, "IX_Menus_ParentId");

                    b.HasIndex(new[] { "SortOrder" }, "IX_Menus_SortOrder");

                    b.HasIndex(new[] { "Code" }, "UQ_Menus_Code")
                        .IsUnique();

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.MenuPermission", b =>
                {
                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("ANY");

                    b.HasKey("MenuId", "PermissionId");

                    b.HasIndex(new[] { "PermissionId" }, "IX_MenuPermissions_PermissionId");

                    b.ToTable("MenuPermissions");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__Message__3214EC07A6F47866");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Specificity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ByAssignment");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "UQ_Permissions_Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateAT")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Public");

                    b.HasKey("Id")
                        .HasName("PK__Post__3214EC07063A806E");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CommunityId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.PostHashtag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("HashtagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__PostHash__3214EC074509FB46");

                    b.HasIndex("HashtagId");

                    b.HasIndex(new[] { "PostId", "HashtagId" }, "UQ_PostHashtag")
                        .IsUnique();

                    b.ToTable("PostHashtag", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("QuotedPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Quote__3214EC07566AA1D9");

                    b.HasIndex("AuthorId");

                    b.HasIndex("QuotedPostId");

                    b.ToTable("Quote", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Reply__3214EC0702D9ABE5");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Reply", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Repost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Repost__3214EC070827F443");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "UQ_Repost")
                        .IsUnique();

                    b.ToTable("Repost", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Roles_Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex(new[] { "PermissionId" }, "IX_RolePermissions_PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Timezone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Continente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiferenciaUtf")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DiferenciaUTF");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Timezone__3214EC0738601550");

                    b.ToTable("Timezone", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BannerPictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("PinnedPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TimezoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC0729ABEF16");

                    b.HasIndex("CityId");

                    b.HasIndex("PinnedPostId");

                    b.HasIndex("TimezoneId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534FC6E4457")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ__User__C9F284566FA2E5C7")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.UserHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "IX_UserHistory_EntityType");

                    b.HasIndex(new[] { "PerformedBy" }, "IX_UserHistory_PerformedBy");

                    b.HasIndex(new[] { "UserId" }, "IX_UserHistory_UserId");

                    b.ToTable("UserHistory", (string)null);
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "AssignedBy" }, "IX_UserRoles_AssignedBy");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRoles_RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Block", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Blocked")
                        .WithMany("BlockBlockeds")
                        .HasForeignKey("BlockedId")
                        .IsRequired()
                        .HasConstraintName("FK_Block_Blocked");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Blocker")
                        .WithMany("BlockBlockers")
                        .HasForeignKey("BlockerId")
                        .IsRequired()
                        .HasConstraintName("FK_Block_Blocker");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Chat", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "UserHigh")
                        .WithMany("ChatsAsUserHigh")
                        .HasForeignKey("UserHighId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_UserHigh");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "UserLow")
                        .WithMany("ChatsAsUserLow")
                        .HasForeignKey("UserLowId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_UserLow");

                    b.Navigation("UserHigh");

                    b.Navigation("UserLow");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.City", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_City_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Community", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Creator")
                        .WithMany("Communities")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Community_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.CommunityMember", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Community", "Community")
                        .WithMany("CommunityMembers")
                        .HasForeignKey("CommunityId")
                        .IsRequired()
                        .HasConstraintName("FK_CommunityMember_Community");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "User")
                        .WithMany("CommunityMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CommunityMember_User");

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Following", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Followed")
                        .WithMany("FollowingFolloweds")
                        .HasForeignKey("FollowedId")
                        .IsRequired()
                        .HasConstraintName("FK_Following_Following");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Follower")
                        .WithMany("FollowingFollowers")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("FK_Following_Follower");

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Like", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Like_Post");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Like_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.MediaFile", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "Post")
                        .WithMany("MediaFiles")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_MediaFile_Post");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "User")
                        .WithMany("MediaFiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MediaFile_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Mention", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "Post")
                        .WithMany("Mentions")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Mention_Post");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "User")
                        .WithMany("Mentions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Mention_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Menu", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Menu", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Menus_ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.MenuPermission", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Menu", "Menu")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MenuPermissions_Menu");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Permission", "Permission")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MenuPermissions_Permission");

                    b.Navigation("Menu");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Message", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_Chat");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_Sender");

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Post", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Post_Author");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .HasConstraintName("FK_Post_Community");

                    b.Navigation("Author");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.PostHashtag", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Hashtag", "Hashtag")
                        .WithMany("PostHashtags")
                        .HasForeignKey("HashtagId")
                        .IsRequired()
                        .HasConstraintName("FK_PostHashtag_Hashtag");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "Post")
                        .WithMany("PostHashtags")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_PostHashtag_Post");

                    b.Navigation("Hashtag");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Quote", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Author")
                        .WithMany("Quotes")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Quote_Author");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "QuotedPost")
                        .WithMany("Quotes")
                        .HasForeignKey("QuotedPostId")
                        .IsRequired()
                        .HasConstraintName("FK_Quote_Post");

                    b.Navigation("Author");

                    b.Navigation("QuotedPost");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Reply", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "Author")
                        .WithMany("Replies")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Reply_Author");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "Post")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Reply_Post");

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Repost", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "Post")
                        .WithMany("Reposts")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Repost_Post");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "User")
                        .WithMany("Reposts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Repost_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.RolePermission", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permission");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.User", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_User_City");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Post", "PinnedPost")
                        .WithMany("Users")
                        .HasForeignKey("PinnedPostId")
                        .HasConstraintName("FK_User_PinnedPost");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Timezone", "Timezone")
                        .WithMany("Users")
                        .HasForeignKey("TimezoneId")
                        .HasConstraintName("FK_User_Timezone");

                    b.Navigation("City");

                    b.Navigation("PinnedPost");

                    b.Navigation("Timezone");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.UserHistory", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "PerformedByNavigation")
                        .WithMany("UserHistoryPerformedByNavigations")
                        .HasForeignKey("PerformedBy")
                        .HasConstraintName("FK_UserHistory_PerformedBy");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "User")
                        .WithMany("UserHistoryUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserHistory_User");

                    b.Navigation("PerformedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.UserRole", b =>
                {
                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "AssignedByNavigation")
                        .WithMany("UserRoleAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK_UserRoles_AssignedBy");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Role");

                    b.HasOne("XClone.Domain.Database.SqlServer.Entities.User", "User")
                        .WithMany("UserRoleUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_User");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Community", b =>
                {
                    b.Navigation("CommunityMembers");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Hashtag", b =>
                {
                    b.Navigation("PostHashtags");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Menu", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Permission", b =>
                {
                    b.Navigation("MenuPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Post", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("MediaFiles");

                    b.Navigation("Mentions");

                    b.Navigation("PostHashtags");

                    b.Navigation("Quotes");

                    b.Navigation("Replies");

                    b.Navigation("Reposts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.Timezone", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("XClone.Domain.Database.SqlServer.Entities.User", b =>
                {
                    b.Navigation("BlockBlockeds");

                    b.Navigation("BlockBlockers");

                    b.Navigation("ChatsAsUserHigh");

                    b.Navigation("ChatsAsUserLow");

                    b.Navigation("Communities");

                    b.Navigation("CommunityMembers");

                    b.Navigation("FollowingFolloweds");

                    b.Navigation("FollowingFollowers");

                    b.Navigation("Likes");

                    b.Navigation("MediaFiles");

                    b.Navigation("Mentions");

                    b.Navigation("Messages");

                    b.Navigation("Posts");

                    b.Navigation("Quotes");

                    b.Navigation("Replies");

                    b.Navigation("Reposts");

                    b.Navigation("UserHistoryPerformedByNavigations");

                    b.Navigation("UserHistoryUsers");

                    b.Navigation("UserRoleAssignedByNavigations");

                    b.Navigation("UserRoleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
